name: Qwhitelist     
main: com.Qwhitelist.Qwhitelist  
version: 0.9.8
commands:
   Qwl: #试图有指令qaq
     description: "Qwhitelist help"
     usage: /Qwl
   Qwl add:
     description: "Qwhitelist add name"
     usage: "/Qwl add name"
   Qwl remove:
     description: "Qwhitelist remove name"
     usage: "/Qwl remove name"
   